

# Script generated by  B u i l d  A s s i s t a n t
mkdir -p bin
mkdir -p ./bin/Linux


printf "\n========== hair.c\n"
clang hair.c -o ./bin/Linux/hair -Os -s -lm -lncurses


printf "\n========== typespeed.c\n"
clang typespeed.c -o ./bin/Linux/typespeed -Os -s -lm -lncurses


printf "\n========== hr_sim_2\n"
cd hr_sim_2
cargo build --release 
cp target/release/hr_sim_2 ../bin/Linux/hr_sim_2
cargo clean
cd ..


printf "\n========== 250327.c\n"
clang 250327.c -o ./bin/Linux/250327 -Os -s -lm -lncurses
