

# Script generated by  B u i l d  A s s i s t a n t
mkdir -p bin
mkdir -p ./bin/Darwin


printf "\n========== hair.c\n"
clang hair.c -o ./bin/Darwin/hair -std=c23 -Wall -Wextra -Os -s -lm -lncurses


printf "\n========== hr_sim_2\n"
cd hr_sim_2
cargo build --release 
cp target/release/hr_sim_2 ../bin/Darwin/hr_sim_2
cargo clean
cd ..


printf "\n========== typespeed.c\n"
clang typespeed.c -o ./bin/Darwin/typespeed -std=c23 -Wall -Wextra -Os -s -lm -lncurses


printf "\n========== 250327.c\n"
clang 250327.c -o ./bin/Darwin/250327 -std=c23 -Wall -Wextra -Os -s -lm -lncurses


printf "\n========== joyrun.c\n"
clang joyrun.c -o ./bin/Darwin/joyrun -std=c23 -Wall -Wextra -Os -s -lm -lncurses
