

# Script generated by  B u i l d  A s s i s t a n t
mkdir -p bin
mkdir -p bin/Linux

printf "\n========== hair.c\n"
clang hair.c -o ./bin/Linux/hair -lm -lncurses

printf "\n========== typespeed.c\n"
clang typespeed.c -o ./bin/Linux/typespeed -lm -lncurses

printf "\n========== test.rs\n"
rustc test.rs -o ./bin/Linux/test 

printf "\n========== shit\n"
cd shit
cargo build --release 
cp target/release/shit ../bin/Linux/shit
cd ..
