

# Script generated by  B u i l d  A s s i s t a n t
mkdir -p bin
mkdir -p ./bin/Windows


printf "\n========== 250327.c\n"
clang 250327.c -o ./bin/Windows/250327.exe -Os -s -lm -lncursesw


printf "\n========== hair.c\n"
clang hair.c -o ./bin/Windows/hair.exe -Os -s -lm -lncursesw


printf "\n========== hr_sim_2\n"
cd hr_sim_2
cargo build --release 
cp target/release/hr_sim_2.exe ../bin/Windows/hr_sim_2.exe
cargo clean
cd ..


printf "\n========== typespeed.c\n"
clang typespeed.c -o ./bin/Windows/typespeed.exe -Os -s -lm -lncursesw
