

# Script generated by  B u i l d  A s s i s t a n t
mkdir -p bin
mkdir -p ./bin/Windows


printf "\n========== hair.c\n"
clang hair.c -o ./bin/Windows/hair.exe -Os -s -lm -lncursesw


printf "\n========== typespeed.c\n"
clang typespeed.c -o ./bin/Windows/typespeed.exe -Os -s -lm -lncursesw
